using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Saas.Infra.MVC.Services.Blazor;

namespace Saas.Infra.MVC.Controllers.Api
{
    /// <summary>
    /// Controller used to complete Blazor authentication handoff.
    /// Accepts a short-lived code from <see cref="BlazorAuthHandoffService"/>,
    /// issues the HTTP-only authentication cookie, and redirects back to the Blazor route.
    /// </summary>
    [ApiController]
    [Route("blazor")] 
    public sealed class BlazorAuthController : ControllerBase
    {
        private readonly BlazorAuthHandoffService _handoffService;
        private readonly ILogger<BlazorAuthController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="BlazorAuthController"/> class.
        /// </summary>
        /// <param name="handoffService">Handoff service used to resolve one-time codes to tokens.</param>
        /// <param name="logger">Logger instance.</param>
        /// <exception cref="ArgumentNullException">Thrown when dependencies are null.</exception>
        public BlazorAuthController(BlazorAuthHandoffService handoffService, ILogger<BlazorAuthController> logger)
        {
            _handoffService = handoffService ?? throw new ArgumentNullException(nameof(handoffService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Consumes a one-time handoff code, sets the auth cookie, and redirects to the target route.
        /// </summary>
        /// <param name="code">One-time handoff code generated by the Blazor login component.</param>
        /// <param name="returnUrl">Target route to navigate to after establishing auth.</param>
        /// <returns>Redirect result to the specified returnUrl, or 400/302 back to login on failure.</returns>
        [HttpGet("establish-auth")]
        public IActionResult EstablishAuth([FromQuery] string? code, [FromQuery(Name = "return")] string? returnUrl)
        {
            if (string.IsNullOrWhiteSpace(code))
            {
                _logger.LogWarning("Blazor auth handoff attempted with empty code.");
                return Redirect("/account/login");
            }

            var token = _handoffService.ConsumeHandoff(code);
            if (string.IsNullOrWhiteSpace(token))
            {
                _logger.LogWarning("Blazor auth handoff failed for code {Code}", code);
                return Redirect("/account/login");
            }

            // Issue HttpOnly cookie so subsequent HTTP requests can access the token.
            var cookieOptions = new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
                SameSite = SameSiteMode.Strict,
                Expires = DateTimeOffset.UtcNow.AddHours(1)
            };

            Response.Cookies.Append("AccessToken", token, cookieOptions);
            _logger.LogInformation("Blazor auth cookie established via handoff.");

            // Normalise returnUrl to a safe application-relative path.
            var target = string.IsNullOrWhiteSpace(returnUrl) ? "/dashboard" : returnUrl;
            if (!target.StartsWith("/", StringComparison.Ordinal))
            {
                target = "/" + target;
            }

            return Redirect(target);
        }
    }
}
