using System;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Saas.Infra.Core;
using Saas.Infra.MVC.Services.Blazor;

namespace Saas.Infra.MVC.Controllers.Api
{
    /// <summary>
    /// Controller used to complete Blazor authentication handoff.
    /// Accepts a short-lived code from <see cref="BlazorAuthHandoffService"/>,
    /// issues the HTTP-only authentication cookie, and redirects back to the Blazor route.
    /// </summary>
    [ApiController]
    [Route("blazor")]
    public sealed class BlazorAuthController : ControllerBase
    {
        private readonly BlazorAuthHandoffService _handoffService;
        private readonly ILogger<BlazorAuthController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="BlazorAuthController"/> class.
        /// </summary>
        /// <param name="handoffService">Handoff service used to resolve one-time codes to tokens.</param>
        /// <param name="logger">Logger instance.</param>
        /// <exception cref="ArgumentNullException">Thrown when dependencies are null.</exception>
        public BlazorAuthController(BlazorAuthHandoffService handoffService, ILogger<BlazorAuthController> logger)
        {
            _handoffService = handoffService ?? throw new ArgumentNullException(nameof(handoffService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Consumes a one-time handoff code, sets the auth cookie, and redirects to the target route.
        /// </summary>
        /// <param name="code">One-time handoff code generated by the Blazor login component.</param>
        /// <param name="returnUrl">Target route to navigate to after establishing auth.</param>
        /// <returns>Redirect result to the specified returnUrl, or 400/302 back to login on failure.</returns>
        [HttpGet("establish-auth")]
        public IActionResult EstablishAuth([FromQuery] string? code, [FromQuery(Name = "return")] string? returnUrl)
        {
            if (string.IsNullOrWhiteSpace(code))
            {
                _logger.LogWarning("Blazor auth handoff attempted with empty code.");
                return Redirect("/account/login");
            }

            var token = _handoffService.ConsumeHandoff(code);
            if (string.IsNullOrWhiteSpace(token))
            {
                _logger.LogWarning("Blazor auth handoff failed for code {Code}", code);
                return Redirect("/account/login");
            }

            var cookieOptions = new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
                // Stripe redirects back from a third-party domain. Lax allows the auth cookie
                // on top-level cross-site navigations while still protecting subresource CSRF.
                SameSite = SameSiteMode.Lax,
                Expires = DateTimeOffset.UtcNow.AddHours(1)
            };

            Response.Cookies.Append("AccessToken", token, cookieOptions);
            _logger.LogInformation("Blazor auth cookie established via handoff.");

            var target = string.IsNullOrWhiteSpace(returnUrl)
                ? GetDefaultDashboardRoute(token)
                : returnUrl;
            if (!target.StartsWith("/", StringComparison.Ordinal))
            {
                target = "/" + target;
            }

            return Redirect(target);
        }

        /// <summary>
        /// Deletes the auth cookie and redirects to the login page.
        /// Called by the Blazor logout flow after clearing the in-memory token.
        /// </summary>
        /// <returns>Redirect to the login page.</returns>
        [HttpGet("clear-auth")]
        public IActionResult ClearAuth()
        {
            Response.Cookies.Delete("AccessToken");
            _logger.LogInformation("Blazor auth cookie cleared. Redirecting to login.");
            return Redirect("/account/login");
        }

        private static string GetDefaultDashboardRoute(string token)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                return "/dashboard";
            }

            try
            {
                var jwt = new JwtSecurityTokenHandler().ReadJwtToken(token);
                var roleCodes = jwt.Claims
                    .Where(claim => string.Equals(claim.Type, "role", StringComparison.OrdinalIgnoreCase)
                                    || string.Equals(claim.Type, System.Security.Claims.ClaimTypes.Role, StringComparison.OrdinalIgnoreCase))
                    .Select(claim => claim.Value)
                    .ToList();

                if (roleCodes.Any(role => string.Equals(role, RoleCodes.SuperAdmin, StringComparison.OrdinalIgnoreCase)))
                {
                    return "/super-admin";
                }

                if (roleCodes.Any(role => string.Equals(role, RoleCodes.Admin, StringComparison.OrdinalIgnoreCase)))
                {
                    return "/admin";
                }
            }
            catch
            {
                return "/dashboard";
            }

            return "/dashboard";
        }
    }
}
